version: '3'
services:
  web:
    image: bagusajah/tvlktht:website
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: fluentd  
      options:
        fluentd-address: localhost:24224
        tag: nginx_access
    networks:
      - tvlktht
    depends_on:  
      - "fluentd"

  fluentd:
    image: bagusajah/tvlktht:fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
    networks:
      - tvlktht
    depends_on:
      - "elasticsearch"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - tvlktht

  kibana:
    image: kibana:7.2.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - tvlktht

networks:
  tvlktht: