apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: webapp-default
spec:
  type: "LoadBalancer"
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    name: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: webapp-default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bagusajah/tvlktht:website
        ports:
        - containerPort: 80